### ISSUE TITLE
Add rulesets

### ISSUE THREAD

**Issue by frickelbruder** [frickelbruder/kickoff#31]
There should be a new main area:
Rulesets

Each rule set should consist of a name and one or more rule assigned rules. Example:
```
Rulesets:
    - security:
            - ValidSslCertificate
            - HttpHeaderXSSProtectionSecure
            - HttpHeaderExposeLanguage
```

Those rulesets can be referenced in each section ( additionally to normal rules ). Example:
```
Sections:
    website:
         rulesets:
             - security
             - seo
         rules:
            - HttpHeaderHasEtag
            - HttpHeaderResourceFound
```
